.prettierrc.mjs, README.md, astro.config.mjs, eslint.config.mjs, package-lock.json, package.json, src/components/Welcome.astro, src/layouts/Layout.astro, src/pages/index.astro
=> setup eslint and prettier

package-lock.json, package.json, src/consts.ts, src/esa-utils/faq-parser.ts, src/esa-utils/models.ts, src/layouts/Layout.astro, src/pages/faq.astro, src/pages/posts/[id].astro
=> unified ライブラリを使用して個別記事ページの描画とFAQのパース処理を行う

.vscode/extensions.json, .vscode/settings.json, package-lock.json, package.json, src/components/ArticleCard.astro, src/esa-utils/thumbnail.ts, src/layouts/Layout.astro, src/pages/index.astro
=> Card component

astro.config.mjs, package-lock.json, package.json, public/robots.txt
Google等の検索エンジンに情報を与えるため、サイトマップの設定および`robots.txt`を追加した
=> サイトマップの設定を追加

README.md
=> READMEファイルを2025年3月20日時点に適合するようにアップデートした

src/pages/index.astro
fix #28 
index.astroの中でfaqのcardにstyleをつけました
=> faqのcardを作りました

src/pages/index.astro, src/pages/posts/[id].astro
fix #16 
postsからfilter()でfaqを取り除いた
=> 記事一覧からfaqを消す

public/favicon.svg
fix #24
faviconを去年の新入生情報ウェブと同じものにしました
=> faviconを修正する

src/pages/index.astro
fix #40 fix #42 
お問い合わせフォームのリンクを指定しました
ソースコードへのリンクを貼りました
=> 問い合わせフォーム、リポジトリのリンクの追加

src/components/ArticleCard.astro, src/components/Card.astro, src/pages/index.astro
=> Card コンポーネントを追加して同じスタイルの部分を書き直す

src/layouts/Layout.astro, src/pages/posts/[id].astro
=> Adjust img article pages

src/pages/index.astro
"記事一覧"がcard-containerの中に入っていなかったので入れた
=> 記事一覧をcard-containerの内部に追加

src/pages/faq.astro
他のページと同様、以下の形にした。
- そのページの名前のみ
- aタグはつけない
=> faqページのタイトルを修正

src/pages/faq.astro, src/pages/index.astro, src/pages/posts/[id].astro
#57 記事ページ本体の幅を以下の様にしました
PC: widthを620pxにし、marginを8px設ける
その他 : widthを100%にし、marginを8px設ける
=> サイトのタイトル以外の幅を調節しました

src/pages/index.astro
fix #64 
containerのpaddingを設定しました
=> index.astroにmarginをつける

src/layouts/Layout.astro
og:titleを指定していないと、OGP画像が表示されない場合があるため
=> `og:title`を追加

src/layouts/Layout.astro
=> og:title を出力するようにした

src/components/Header.astro, src/layouts/Layout.astro, src/pages/faq.astro, src/pages/index.astro, src/pages/posts/[id].astro
新入生歓迎Web2024 を多大に参考にしつつ heading にスタイルをつけた
=> Style headings

src/esa-utils/hash.ts, src/pages/faq.astro
=> refactor: hash related function as a separated file

src/layouts/Layout.astro, src/pages/posts/[id].astro
=> JSON-LDの値を追加

public/robots.txt
#23 が解決する以前はGoogleに誤って画像をクロールさせないような設定をしていたが、これが解決したためGoogleに画像もクロール可能なように変更
=> Googleに画像もクロールさせるように変更

src/components/Card.astro, src/esa-utils/optimize-image.ts, src/esa-utils/thumbnail.ts
=> Set image width, height to prevent layout shift

src/consts.ts
=> Change site title

src/components/footer.astro, src/layouts/Layout.astro, src/pages/faq.astro, src/pages/index.astro, src/pages/posts/[id].astro
=> Simplify footer

src/components/footer.astro, src/pages/faq.astro, src/pages/posts/[id].astro
=> Fix logo padding

src/components/Toc.astro, src/pages/faq.astro
FAQ ページのみ目次の番号を出し、他のページでは目次番号を消す
=> Show Toc number on FAQ page

src/assets/linkage_icon_rect.svg, src/assets/linkage_icon_square.svg
外部リンクにアイコンを添えたいが、丁度良いものが好都合なライセンスでころがっていなかったので自作
アイコンそのものはページ上に配置してから微調整の予定
=> 外部リンクに添える仮アイコンを追加
